
log_level="debug"

[[streamconfigs]]
ip = "0.0.0.0"
port = 9000
mode = "Periodic"
volume = 20
input_format = "JSON"
output_format = "JSON"
data_folder = "./data/flow"

[[streamconfigs]]
ip = "0.0.0.0"
port = 9001
mode = "Periodic"
volume = 20
input_format = "JSON"
output_format = "JSON"
data_folder = "./data/speed"

