[[streamconfigs]]
ip = "localhost"
port = 9000
mode = "Constant"
volume = 2
data_folder = "./data/flow"

[[streamconfigs]]
ip = "localhost"
port = 9001
mode = "Periodic"
data_folder = "./data/speed"

