[[streamconfigs]]
ip = "localhost"
port = 9000
mode = "Constant"
volume = 1
input_format = "JSON"
output_format = "XML"
data_folder = "./data/flow"

[[streamconfigs]]
ip = "localhost"
port = 9001
mode = "Periodic"
volume = 20
input_format = "JSON"
output_format = "CSV"
data_folder = "./data/speed"

